name: nanomvvm # Renomeado para nanomvvm
description: A minimalist MVVM library for Flutter, inspired by .NET BindingContext.
version: 0.0.1
homepage: https://github.com/your_username/nanomvvm # Ajuste para o seu repositório

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# publish_to: 'none' # Remova esta linha se for publicar